---
engines:
  golint:
    enabled: true
    checks:
      GoLint/Naming/MixedCaps:
        enabled: false
  govet:
    enabled: true
  gofmt:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - "context.go" # go 1.9
  - "/code/context.go" # go 1.9
  - "_examples/**/*"
  - "vendor/**/*"
  - "ionic/**/*"
  - "**/*_test.go"